### ISSUE TITLE
Hyperion on openelec not working

### ISSUE THREAD

**Issue by posthok** [WeeJeWel/net.weejewel.hyperion#7]
Homey 1.02
I've got a lightberry installed on a raspberry pi b+ with openelec  (OpenELEC-5.0.RPi.arm-Bplus_stk1160)
But this version of the app is not working with it.
It's connecting though, but that's all.

**Comment by WeeJeWel** [comment]
I am not running OpenELEC so I can't debug for you. Maybe they're using an older version.

This is a 'free-time' project of mine, so please try to do some debugging yourself!

**Comment by posthok** [comment]
I'll tried it, but this is the result     

(https://cloud.githubusercontent.com/assets/6661318/20933885/b156e21a-bbd9-11e6-88f4-438dae77c6b9.png)

Hyperion running...
Error: Cannot find module 'hyperion-client'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/drivers/hyperion/driver.js:3:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

--- INFO: net.weejewel.hyperion has been killed ---
C:\Users\Node\Desktop\hyperion>
